-- Esquema do banco do Mio da Feada (Supabase / Postgres).
-- Serve para recriar o projeto do zero: cole no SQL Editor de um projeto novo e rode UMA vez.
--
-- ANTES DE RODAR: troque 00000000-0000-0000-0000-000000000000 (aparece 9 vezes) pelo UUID do
-- usuário-autor (Supabase > Authentication > Users > coluna "User UID"). Só esse usuário
-- escreve; os visitantes só leem o que está publicado.
--
-- Depois: restaure os dados com  node scripts/restore.mjs <pasta-do-backup> --apply

-- updated_at automático ---------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Sessões de campanha (Campanha > Arco > Sessão) ---------------------------------------
create table public.sessoes (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  title       text not null,
  campaign    text,
  arc         text,
  session     integer,
  date        date not null,
  tags        text[],
  summary     text,
  content     text,
  published   boolean not null default false
);
create index sessoes_date_idx on public.sessoes (date, created_at);
create index sessoes_campaign_arc_idx on public.sessoes (campaign, arc, session);

-- Tomos do Storyteller (árvore: cada tomo aponta para o pai) ---------------------------
create table public.tomos (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  parent_id   bigint references public.tomos(id) on delete restrict,
  position    integer not null default 0,
  title       text not null,
  summary     text,
  content     text,
  tags        text[],
  published   boolean not null default false,
  constraint tomos_nao_e_pai_de_si_mesmo check (parent_id is null or parent_id <> id)
);
create index tomos_parent_idx on public.tomos (parent_id, position);

-- Personagens (ficha estilo currículo; foto no Storage) --------------------------------
create table public.personagens (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  name         text not null,
  bio          text,
  race         text,
  age          text,
  birthplace   text,
  class        text,
  affiliation  text,
  story        text,
  photo_url    text,
  published    boolean not null default false
);
create index personagens_name_idx on public.personagens (name);

create trigger sessoes_set_updated_at     before update on public.sessoes     for each row execute function public.set_updated_at();
create trigger tomos_set_updated_at       before update on public.tomos       for each row execute function public.set_updated_at();
create trigger personagens_set_updated_at before update on public.personagens for each row execute function public.set_updated_at();

-- Acesso: visitante lê só o publicado; o autor lê e escreve tudo -----------------------
alter table public.sessoes     enable row level security;
alter table public.tomos       enable row level security;
alter table public.personagens enable row level security;

create policy "leitura_publica_publicados" on public.sessoes     for select to anon using (published);
create policy "leitura_publica_publicados" on public.tomos       for select to anon using (published);
create policy "leitura_publica_publicados" on public.personagens for select to anon using (published);

create policy "autor_tudo" on public.sessoes for all to authenticated
  using ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid)
  with check ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
create policy "autor_tudo" on public.tomos for all to authenticated
  using ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid)
  with check ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
create policy "autor_tudo" on public.personagens for all to authenticated
  using ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid)
  with check ((select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);

-- Fotos dos personagens: bucket público (leitura pela URL), até 2 MB, só imagens -------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('personagens', 'personagens', true, 2097152, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

create policy "personagens_fotos_autor_insere" on storage.objects for insert to authenticated
  with check (bucket_id = 'personagens' and (select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
create policy "personagens_fotos_autor_atualiza" on storage.objects for update to authenticated
  using (bucket_id = 'personagens' and (select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
create policy "personagens_fotos_autor_apaga" on storage.objects for delete to authenticated
  using (bucket_id = 'personagens' and (select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid);
